CREATE EXTENSION IF NOT EXISTS "pg_uuidv7";

CREATE TABLE auth (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    username VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
