// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
	LastUpdated  pgtype.Timestamptz
}

type OauthIdentity struct {
	ProviderUserID string
	Provider       string
	UserID         pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}
